# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9568f2453e3b95cb34690eb0e7277fae9afe92fa4b62551b31f03f0de8ae9847248ff20098f58fb2cdcd1e8aa71c0bc4a557ed5e9e2db02737a56a584c7905a2

test:
  secret_key_base: 8cbd270d887c00c1e1fd7e0d8a6661c3ca9304d5a27762433b7730d6c1bdec68fae1ecb98d15a9da5726506f09d9ae593a1c83ce41ab1612482ebc1117d62c3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
